name: Release integration

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    name: Build, push and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: gradle

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Log in to OpenShift
        run: oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ vars.OPENSHIFT_SERVER }}

      - name: Check environment
        id: environment
        run: echo "environment=$(echo "${{ github.ref_name }}" | cut -d '/' -f1)" >> $GITHUB_OUTPUT

      - name: Check version
        id: version
        run: echo "version=$(echo "${{ github.ref_name }}" | cut -d '/' -f2)" >> $GITHUB_OUTPUT

      - name: Build, push and deploy
        run: |
          cicd/application-release.sh "${{ steps.environment.outputs.environment }}" "${{ steps.version.outputs.version }}"