name: Build, push and deploy

on:
  push:
    branches:
      - 'develop'
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    name: Build, push and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # It exists a fetch-tags, but currently it is experiencing issues https://github.com/actions/checkout/issues/1471

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: gradle

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Log in to OpenShift
        run: oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ vars.OPENSHIFT_SERVER }}

      - name: Build, push and deploy
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          environment="$(.stages/resolve-environment.sh "${{ github.ref_name }}")"
          version="$(.stages/resolve-version.sh "${{ github.ref_name }}")"
          .stages/integration-stage.sh "${environment}" "${version}"