name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - 'develop'
          - 'release'
          - 'hotfix'
        description: Environment
        required: true

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: gradle

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Log in to OpenShift
        run: oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ vars.OPENSHIFT_SERVER }}

      - name: Deploy
        run: .stages/promotion-stage.sh ${{ inputs.environment }}