name: Pull request

on:
  pull_request:
    branches:
      - 'develop'
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: gradle

      - name: Build and run tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: .stages/commit-stage.sh "${{ github.event.pull_request.head.ref }}"
